export const RestrictedWords = [
  'Email',
  'Personal email',
  'Personal contact',
  'WhatsApp',
  'Telegram',
  'Signal',
  'Viber',
  'Line app',
  'Social media',
  'Facebook',
  'Instagram',
  'IG',
  'Twitter',
  'Snapchat',
  'LinkedIn',
  'Personal address',
  'Transaction outside',
  'Booking directly',
  'Book outside',
  'Order outside',
  'Arrange payment',
  'Directly pay',
  'Contact info',
  'Reach me at',
  'Skype',
  'WeChat',
  'Contact through',
  'Social contact',
  'Private message',
  'DM on',
  'Contact details',
  'Snap me',
  'Insta me',
  'FB message',
  'Twitter handle',
  'Insta handle',
  'Private chat',
  'Chat me up',
  'Find me on',
  'Reach out via',
  'Message me at',
  'Contact outside',
  'Outside contact',
  'Meet in person',
  'Offline contact',
  'Outside communication',
  'External contact',
  'Alternative contact',
  'Message externally',
  'Contact via',
  'Outside booking',
  'Book me on',
  'Meet directly',
  'Arrange outside',
  'Communication outside',
  'Platform bypass',
  'Avoid using platform',
  'Contact directly',
  'Phone number',
  'Call me',
  'Text me',
  'Contact me at',
  'PayPal',
  'Venmo',
  'Cash',
  'Cash app',
  'Zelle',
  'DM',
  'Wire transfer',
  'Bank transfer',
  'DM me',
  'Direct payment',
  'Outside payment',
  'Off app',
  'Invoice outside',
  'Pay offline',
  'Pay direct',
  'Marketplace Monetization 5',
  'Avoid fee',
  'Avoid commission',
  'No fee',
  'Discount for cash',
  'Pay in person',
  'Directly',
  'V e nm o',
  'C.a.sh app',
  'C.a.shapp',
  'I.G.',
  'I.N.S.T.A.G.R.A.M.',
  'Inst.a.gr.am',
  'Send money',
  'Transfer funds',
  'Cash deal',
  'Outside platform',
  'Direct deposit',
  'Payment link',
  'Money order',
  'Western Union',
  'Avoid charges',
  'No platform fee',
  'Reduced rate',
  'Cash payment',
  'Payment outside',
  'Non-platform payment',
  'Pay through',
  'Direct transfer',
  'Pay externally',
  'Platform fee avoidance',
  'Cash transaction',
  'External invoice',
  'Alternative payment',
  'External payment',
  'line.me',
  't.me',
  'facebook.com',
  'fb.com',
  'f.b.',
  'instagram.com',
  'insta.com',
  'ig.com',
  'i.g.',
  'twitter.com',
  'twtr.com',
  'linkedin.com',
  'snapchat.com',
  'snap.com',
  'whatsapp.com',
  'telegram.org',
  'line.me',
  't.me',
]
