export const ROUTES = {
  home: '/',
  error404: '/404',
  termsAndConditions: '/terms-and-conditions',
  onboarding_client: '/onboarding/client',
  onboarding_professional: '/onboarding/professional',
  setup_pro: '/onboarding/setup-pro',
  inspiration: '/inspiration',
  search: '/search',
  user: '/user',
  profile: (id: string) => `/profile/${id}`,
  booking: (id: string) => `/booking/${id}`,
  bookings: '/bookings',
  messages: '/messages',
  notifications: '/notifications',
  favorites: '/user/favorites',
  myProfile: '/user/',
  forgotPassword: '/forgot-password',
  termsOfServices: '/terms-of-services',
  upgradeSubscription: '/upgrade-subscription',
  cancellationPolicy: '/cancellation-policy',
  privacyPolicy: '/privacy-policy',
  faq: '/faq',
  notListedPro: '/not-listed-pro',
}
